title: dxdez
email: dylan.x.h.developer@gmail.com 
description: >- 
  The profile page for dxdez. I use this platform to share my notes and my work.
baseurl: "" 
url: "" 
github_username:  dxdez
linkedin_username: dxdez

theme: slate
plugins:
  - jekyll-feed

